### ISSUE TITLE
[TAG] Inconsistent terminology between Explainer and Spec

### ISSUE THREAD

**Issue by slightlyoff** [WICG/feature-policy#73] opened 2017-04-28 06:53 UTC
[From TAG review](https://github.com/w3ctag/design-reviews/issues/159)

The terms used in the Explainer and the spec are not consistent. Some examples in the explainer use `enable` and `disable` attributes, whereas the draft spec includes only `allow`

**Comment by clelland** [comment] 2017-05-01 17:42
Is this a duplicate of #72?

**Closed** 2017-05-24 14:24 UTC
